version: '1'

services:
  db:
    container_name: mysql-travel-agency
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: travel_agency_features_db
      MYSQL_ROOT_PASSWORD: R=d36nM}
    command: --secure-file-priv=/images
    volumes:
      - ./src/main/resources/images:/images